### ISSUE TITLE
AWS auth does not work as per instructions

### ISSUE THREAD

**Issue by wahlfeld10x** [awslabs/dynein#108] opened 2022-09-16 05:02 UTC
The [instructions](https://github.com/awslabs/dynein#prerequisites---aws-credentials) say:

```
How to Use

Prerequisites - AWS Credentials

First of all, please make sure you've already configured AWS Credentials in your environment. dynein depends on [rusoto](https://github.com/rusoto/rusoto) and rusoto [can utilize standard AWS credential toolchains](https://github.com/rusoto/rusoto/blob/master/AWS-CREDENTIALS.md) - for example ~/.aws/credentials file, [IAM EC2 Instance Profile](https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_use_switch-role-ec2_instance-profiles.html), or environment variables such as AWS_DEFAULT_REGION / AWS_ACCESS_KEY_ID / AWS_SECRET_ACCESS_KEY / AWS_PROFILE.

One convenient way to check if your AWS credential configuration is ok to use dynein is to install and try to execute [AWS CLI](https://aws.amazon.com/cli/) in your environment (e.g. $ aws dynamodb list-tables). Once you've [configured AWS CLI](https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-configure.html), you should be ready to use dynein.
```

When I try:

```
> aws sts get-caller-identity
{
    "UserId": "<redacted>:curtis.wahlfeld@10xbanking.com",
    "Account": "<redacted>",
    "Arn": "arn:aws:sts::<redacted>:assumed-role/<redacted>/curtis.wahlfeld@10xbanking.com"
}

> aws s3 ls
2021-02-20 04:04:50 <redacted>
2021-02-20 04:04:39 <redacted>
2022-04-20 17:34:26 <redacted>
2022-04-20 17:34:26 <redacted>
2022-07-05 01:10:09 <redacted>
2022-08-25 16:36:38 <redacted>
2022-09-08 08:50:24 <redacted>

> echo $AWS_PROFILE
<redacted>

> echo $AWS_DEFAULT_REGION
eu-west-1

$HOME/.aws/config -->

[profile <redacted>]
azure_tenant_id=<redacted>
azure_app_id_uri=https://signin.aws.amazon.com/saml\#<redacted>
azure_default_username=curtis.wahlfeld@10xbanking.com
azure_default_role_arn=arn:aws:iam::<redacted>:role/<redacted>
azure_default_duration_hours=8
azure_default_remember_me=true
region=eu-west-1

[profile <redacted>]
source_profile=<redacted>
role_arn=arn:aws:iam::<redacted>:role/<redacted>
role_session_name=curtis.wahlfeld@10xbanking.com
region=eu-west-1

> arch
arm64

> file $(which dy)
/Users/curtis.wahlfeld/.local/bin/dy: Mach-O 64-bit executable arm64

> dy --version
dynein 0.2.1

> RUST_LOG=debug RUST_BACKTRACE=1 dy ls
[2022-09-16T05:00:02Z DEBUG dy] Command details: Dynein { child: Some(List { all_regions: false }), region: None, port: None, table: None, shell: false }
[2022-09-16T05:00:02Z DEBUG dy::app] Loading Config File: /Users/curtis.wahlfeld/.dynein/config.yml
[2022-09-16T05:00:02Z DEBUG dy::app] Loaded current config: Config { using_region: None, using_table: None, using_port: None }
[2022-09-16T05:00:02Z DEBUG dy::app] Loading Cache File: /Users/curtis.wahlfeld/.dynein/cache.yml
[2022-09-16T05:00:02Z DEBUG dy::app] Loaded current cache: Cache { tables: None }
[2022-09-16T05:00:02Z DEBUG dy] Initial command context: Context { config: Some(Config { using_region: None, using_table: None, using_port: None }), cache: Some(Cache { tables: None }), overwritten_region: None, overwritten_table_name: None, overwritten_port: None, output: None }
[2022-09-16T05:00:32Z DEBUG dy::control] ListTables API call got an error -- Credentials(
        CredentialsError {
            message: "Couldn't find AWS credentials in environment, credentials file, or IAM role.",
        },
    )
[2022-09-16T05:00:32Z ERROR dy::control] Couldn't find AWS credentials in environment, credentials file, or IAM role.
```

**Comment by StoneDot** [comment] 2022-09-18 09:45
Currently, dynein uses [rusoto](https://github.com/rusoto/rusoto/blob/master/AWS-CREDENTIALS.md) to load AWS credentials. And it seems that you use [aws-azure-login](https://github.com/DTN-Public/aws-azure-login). It looks like that `aws-azure-login` generates `~/.aws/credentials` as described on docs.

> It lets you use the normal Azure AD login (including MFA) from a command line to create a federated AWS session and places the temporary credentials in the proper place for the AWS CLI and SDKs.

Could you check if your `~/.aws/credentials`  is created correctly?

**Comment by wahlfeld10x** [comment] 2022-09-18 22:33
> Currently, dynein uses [rusoto](https://github.com/rusoto/rusoto/blob/master/AWS-CREDENTIALS.md) to load AWS credentials. And it seems that you use [aws-azure-login](https://github.com/DTN-Public/aws-azure-login). It looks like that `aws-azure-login` generates `~/.aws/credentials` as described on docs.
> 
> > It lets you use the normal Azure AD login (including MFA) from a command line to create a federated AWS session and places the temporary credentials in the proper place for the AWS CLI and SDKs.
> 
> Could you check if your `~/.aws/credentials` is created correctly?

Sure, see below. It looks okay to me.

```
> aws-azure-login --profile <redacted> --no-prompt

Logging in with profile '<redacted>'...
Using AWS SAML endpoint https://signin.aws.amazon.com/saml
Assuming role arn:aws:iam::<redacted>:role/<redacted>

> cat $HOME/.aws/credentials | grep <redacted> -A 4

aws_access_key_id=<redacted>
aws_secret_access_key=<redacted>
aws_session_token="<redacted>"
aws_expiration=2022-09-19T02:31:30.000Z

**Comment by wahlfeld10x** [comment] 2022-09-18 22:42
I've just gotten it working. It seems `dy` doesn't work when using `source_profile`. E.g.

```
> aws-azure-login --profile foo --no-prompt
Logging in with profile 'foo'...
Using AWS SAML endpoint https://signin.aws.amazon.com/saml
Assuming role arn:aws:iam::123/foo

> export AWS_PROFILE=foo

> dy ls
(works)

~/.aws/config
[profile bar]
source_profile=foo
role_arn=arn:aws:iam::123:role/foo
role_session_name=curtis.wahlfeld@10xbanking.com
region=eu-west-1

> export AWS_PROFILE=bar

> dy ls
(doesn't work)
```

**Comment by StoneDot** [comment] 2022-09-20 12:26
It makes sense. It seems that `rusoto` does not support `source_profile`. See [the issue](https://github.com/rusoto/rusoto/issues/1559#issuecomment-547027823) for detail. Additionally, it looks like that AWS SDK for Rust support [`source_profile`](https://github.com/awslabs/aws-sdk-rust/blob/f257e6f915fc18f07acf060e83177f91ec6a170d/sdk/aws-config/src/profile/credentials.rs#L112-L121). Thus, to support your use-case, we should change codes to use AWS SDK for Rust instead of `rusoto`. The update to AWS SDK for Rust is tracked by #51.

I will close this issue because we determined the root cause, which should be treated as a feature request of #51. Please feel free to reopen if you have any concerns regarding this issue.

**Closed by StoneDot** 2022-09-20 12:26 UTC

**Comment by wahlfeld10x** [comment] 2022-09-20 22:51
> It makes sense. It seems that `rusoto` does not support `source_profile`. See [the issue](https://github.com/rusoto/rusoto/issues/1559#issuecomment-547027823) for detail. Additionally, it looks like that AWS SDK for Rust support [`source_profile`](https://github.com/awslabs/aws-sdk-rust/blob/f257e6f915fc18f07acf060e83177f91ec6a170d/sdk/aws-config/src/profile/credentials.rs#L112-L121). Thus, to support your use-case, we should change codes to use AWS SDK for Rust instead of `rusoto`. The update to AWS SDK for Rust is tracked by #51.
> 
> I will close this issue because we determined the root cause, which should be treated as a feature request of #51. Please feel free to reopen if you have any concerns regarding this issue.

OK thanks for explaining that. The issue you linked is nearly 3 years old ... is there any ETA from AWS to support this?

**Comment by StoneDot** [comment] 2022-09-24 15:09
There is no ETA currently because AWS SDK for Rust is still beta. Unfortunately, we don't have enough bandwidth to support both SDK at the time.
