### ISSUE TITLE
dy upd fails when right hand statement contains a hyphen

### ISSUE THREAD

**Issue by aphillips19** [awslabs/dynein#114] opened 2023-03-08 18:20 UTC
Using `dynein 0.2.1` on Amazon Linux 2, I am unable to run `dyn upd` to update a string attribute when the new value contains a hyphen. For example, running:

```bash
 dy upd somepk --set 'myattr = "my-value"'
```

gives the error: 
```
[2023-03-08T18:19:45Z ERROR dy::data] failed to parse a right hand statement '"my-value"'. Valid syntax would be: 'Attr = "val"', or 'Attr = Attr + 100'
```

but same command succeeds if I remove the hyphen.

I also tried escaping the hyphen with a backslash, to the same result:

```bash
[2023-03-08T18:20:20Z ERROR dy::data] failed to parse a right hand statement '"my\-value"'. Valid syntax would be: 'Attr = "val"', or 'Attr = Attr + 100'
```

**Comment by StoneDot** [comment] 2023-06-02 14:22
This is a duplicate of #92. I'll close this issue for easy tracking. Thank you for your attention to dynein.

**Closed by StoneDot** 2023-06-02 14:22 UTC
Labels: duplicate
