### ISSUE TITLE
Empty string set failing on export/import

### ISSUE THREAD

**Issue by fab-mindflow** [awslabs/dynein#66] opened 2021-12-25 17:44 UTC
After exporting some of my tables in JSON format, I have the following error when importing:
```
Error: BatchWriteError(Validation("One or more parameter values were invalid: An string set  may not be empty"))
```

It looks like this is due to a string set attribute in the export JSON:
```
    "tags": []
```

The original exported table can contain:
```
  "tags": {
    "L": []
  }
```

In this case, the import fails with the error and stops. Is this expected?

And when the original export is done, the table has a list, not a string set:
```
  "tags": {
    "L": [
      {
        "S": "a-tag"
      }
    ]
  }
```

The import is probably trying to create a String Set attribute (SS) instead of a List attribute (L) due to JSON loss of typing, right? Is there some way to get a full identical table with export then import?

**Comment by StoneDot** [comment] 2022-03-21 16:58
I'm sorry for the delay in response.
As you mentioned, this issue is caused by a loss of the type of empty list. Currently, we have no feature to avoid this issue. We should implement a new format option which compatible with DynamoDB native format.

If you hope to create an identical table, you can use DynamoDB [native backup](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/backuprestore_HowItWorks.html) feature. However, it is not used for a cross-account scenario. In that case, you may use [Data Pipeline](Exporting and Importing DynamoDB Data Using AWS Data Pipeline) or [Glue](https://docs.aws.amazon.com/glue/latest/dg/aws-glue-programming-etl-connect.html#aws-glue-programming-etl-connect-dynamodb).

**Comment by tyyzqmf** [comment] 2023-06-08 02:38
Perhaps this method can help us: `import { marshall } from '@aws-sdk/util-dynamodb';`

**Comment by StoneDot** [comment] 2023-09-30 01:32
The current implementation does not infer a set type because of changes in #147 by default. Thus, I believe this issue is partially resolved. However, we should address the need to copy the items as it is. I created a separate issue #179 to clarify the current problem.

For easy tracking, I will close this issue. Please reopen this issue if you have any other concerns or suggested ways to address your pain.

**Closed by StoneDot** 2023-09-30 01:33 UTC
Labels: enhancement
